### PR TITLE
fixed other employee roles not generating employee badge

### LINKED ISSUE #23: Client Modal - In-Browser image formatting
PTC has discovered that high resolution images render sideways, and need manual cropping in order to properly render on the badge.

I propose we create an in browser solution to handle this.

These two libraries will provide with much of what we need, we will need some kind of wrapper to upload the image to the webpage (Please do not send anything but the cropped/adjusted image to the backend) and then do the cropping.

easy-crop has a few demos to use, image-crop has its api listed out in the npm.
https://www.npmjs.com/package/react-easy-crop
https://www.npmjs.com/package/react-image-crop

### LINKED ISSUE #28: Badge Generator - Adding PTC Logo to center of badge
It would be really cool to have PTC's logo in the center of our badge QR code.

### LINKED ISSUE #31: Badge Generation - Make employee badges generate on all "employee" roles
At the moment the badge generator only creates employee badges if someone is selected as "administrator" or "employee". None of the specific employee roles generate the employee badge on their own.

### LINKED ISSUE #51: Badge Generator - font does not load properly
We're getting an OSError: Can not load resource when trying to generate badges on the PI.

### PR DESCRIPTION
**Pull request by samlovering**
This tidies up the Badge Generator, in addition to fixing some bugs
image

Closes #31 
image

Employee Badges can now be generated through any employee role
image

Closes #23 
There is now the ability to crop and rotate in browser
image

Closes #28 
PTC logo now generates in the badge
image

Closes #51 
The Relative pathing for the  font is now updated correctly with os.path.join

### CODE REVIEW

**Comment by DrewTCurrie** [comment]
Is there anyway to make the QR code look less pixelated near the logo? And make the logo look less pixelated?

**Comment by samlovering** [comment]
@DrewTCurrie I can give it another stab. The QR code library that was picked out doesn't have a image insert option, so I kinda had to hack it together. If worse comes to worse, there will just be no logo in the center

**Comment by DrewTCurrie** [comment]
@samlovering I'll take a stab at it in like an hour. I'll see if I can get something more similar to the QR codes we had on the PPD slides: 
image

But I agree worst case we just do plain QR codes, this shouldn't be a high priority.

**Comment by DrewTCurrie** [comment]
I went through and tried the example code for making nicer looking QR codes on the qrcode package GitHub and they seem broken or out of date. I think we go with it as is for now. Looks like Segno has the features we'd want but I'll review that sometime this upcoming week if I have time.

**Review by DrewTCurrie — APPROVED** [review]
Looks good. Did the garbage collector run without issue on these changes?

**Comment by samlovering** [comment]
I'll reverify it, but there is only about 20 new lines of python code, so it shouldn't affect it

**Pull request merged**
