### PR TITLE
Generate report/dev

### PR DESCRIPTION
**Pull request by DrewTCurrie**
> [!NOTE]
> This version creates an Excel report on the RaspberryPi reliably. However, there are a few quick fixes in the code that need addressed before pushing to dev. 

1. File pathing is now hard-coded as absolute paths. This is not a long term solution. 
2. Database table has been updated in the MariaDB API file. I also created a new standard for the password scheme. 
3. Cross origin is required for now, this again should not be a final solution. As of now, the NodeJS server runs on port ~5173 and the FlaskServer runs on port 5000. I removed references to localhost and changed to the IP of the Pi while testing. This allows the system to work but is not exactly a smooth operation.

>[!WARNING]
>Comments in the previous pull request still are concerns. We need to manage our .gitignore files better. I don't know exactly what files are needed for the front-end but we should try and trim down on the auto-generated files being transferred around. Additionally __init__.py files cause a lot of problems switching OS's so maybe we add these to the .gitignore as well. 

Example of downloaded file: 
CapstoneFirstDownloadedExcelReportonPi

### CODE REVIEW

**Comment by samlovering** [comment]
I think this looks good, although there appears to be a merge conflict with app.tsx.

I will make sure that my .gitignores get updated with the extra node data and pycharm stuff.

**Review by samlovering — APPROVED** [review]
Things look good, I'll update my gitignore locally until this is merged in.

**Comment by DrewTCurrie** [comment]
> I think this looks good, although there appears to be a merge conflict with app.tsx.
> 
> I will make sure that my .gitignores get updated with the extra node data and pycharm stuff.

I think this is because I brought it over from Dev for a quick test and then deleted it in generateReport/dev which is probably causing an issue with git tracking it's removal. I'll go remove this from the dev branch.

**Review by DrewTCurrie — COMMENTED** [review]
I cleaned up the pycache files and added more gitignores to clean up the repo.

**Pull request merged**
