### PR TITLE
Settings + Scanner + 1 Second Delay

### LINKED ISSUE #16: Attendee Interface - Audio Visual Notification System
> [!IMPORTANT]  
> Play some audio and visual notification for successful and unsuccessful check-ins 
> Why: Completion is required to reach SPD

---

**Feature needed:**
Adding support for audio and visual notification for the check-in process. This will allow Attendees to know they checked-in successfully and allow an employee to hear/see if there was an issue with a check-in and intervene.

### LINKED ISSUE #17: Attendee Interface - Scan delay
> [!IMPORTANT]  
> Delay for a few seconds between successful scans to prevent repeated attendance events
> Why: Completion is required to reach SPD

---

**Feature needed:**
Adding a feature to delay between each scan in to prevent duplicate scans. At the moment if the QR code is held in just the right place, the scanner will continue to read the QR code. This will cause multiple attendance events to occur within a few seconds. This could invalidate the data.

### PR DESCRIPTION
**Pull request by samlovering**
A settings page has been created:
image

It automatically displays the default message + default audio being used.

Selecting an attendee, will present a set of attendee specific options:
image

These will either be custom messages + sounds, or the defaults, depending on if it exists in the database.

The scanner has also been reivsed.
image

upon submission, both fields will be locked for 1 second, presenting the message in replace of the normal scanner title.
image

Additionally, a audio will play based on success or failure.
image

The success or failure message will remain on the screen for 5 seconds before disappearing.

It is also set up to refocus the text bar after submission, to ensure that scanner still links to the textbox.
> [!CAUTION]
> The conversion software uses the pydub library, which requires ffmpeg to installed, and likely a full system reset to get the path included. (apt-get ffmpeg) for Debian Linux Systems.

Closes #16 
Closes #17

### CODE REVIEW

**Comment by DrewTCurrie** [comment]
I'll review this later today, I am working on the garbage collector for all the misc. files created during normal operation. I will merge this first into dev then write the garbage collector for this part.

**Comment by DrewTCurrie** [comment]
What should the default data in the database be? I'll need to write some python to automatically populate the database with the defaults otherwise it won't be scalable. Additionally, it just prints errors for the default case since it's not in the database.

**Review by DrewTCurrie — CHANGES_REQUESTED** [review]
Need default values for the database before this can be merged.

**Comment by samlovering** [comment]
image
 
 This is the default
 ID: '0'
 message: "Welcome to PTC"
default Path: flaskServer\static\audioFiles\0.mp3

This can also all be set by using the resetDefaults button

the failure one is '1'.mp3, which has no ability to get changed and is not in the db. It is just the 1.mp3 in the folder.

They have backups with the master.wav files, and can be converted using the convertAudio function to get into mp3s

**Review by DrewTCurrie — APPROVED** [review]

**Comment by DrewTCurrie** [comment]
> [!warning]
> This works as intended however, it causes bug #46
> Closing pull request as it is 99% functional and is sufficient until we need to write a modified garbage collector.

**Comment by DrewTCurrie** [comment]
Accidentally closed without merging....

**Pull request merged**
