### PR TITLE
createAttendee/dev merge

### PR DESCRIPTION
**Pull request by samlovering**
This feature adds the ability to create an Attendee through the UI.

Upon hitting "Create new Attendee" the user will be prompted with this button.
image

This is for a client, where the only information need is a name and role.
Selecting Administrator or an Employee Role would display the following.

Employee:
image

Administrator
image

Upon filling out relevant information and submitting, the following badge will be generated
image

Clicking print will open a new window where the view is expanded and is printable:
image

This for the badge changes based on employee or client, and will display 1 page or two based on what is selected.

### CODE REVIEW

**Comment by samlovering** [comment]
Commit [c52dff0](https://github.com/DrewTCurrie/55ATAT/pull/3/commits/c52dff07810561467aee2f696867f501cf9d4f51) added
node_modules to both the ptcClient and shell-scripts folder again. This will need to be fixed before merging.

**Comment by samlovering** [comment]
I think that node_modules is cleaned up here. In the future, please don't merge work in progress branches into active pull requests. Rebase your new /dev branch off of what you want get from and just create another PR pointing to dev

**Comment by DrewTCurrie** [comment]
> [!CAUTION]
> Font is not rendering properly on the Pi. Can you guys check if the font is still an issue on windows?

[BadFont_Employee.pdf](https://github.com/user-attachments/files/17268507/BadFont_Employee.pdf)
[BadFont_Client.pdf](https://github.com/user-attachments/files/17268509/BadFont_Client.pdf)

**Comment by DrewTCurrie** [comment]
> Caution
> 
> Font is not rendering properly on the Pi. Can you guys check if the font is still an issue on windows?
> 
> [BadFont_Employee.pdf](https://github.com/user-attachments/files/17268507/BadFont_Employee.pdf) [BadFont_Client.pdf](https://github.com/user-attachments/files/17268509/BadFont_Client.pdf)

Fixed with hotfixes in [#C965c74](https://github.com/DrewTCurrie/55ATAT/pull/3/commits/c965c74bae829d0f37430c72d95ad96fd875fc1b)

**Pull request merged**
