### PR TITLE
Updated badge generator/dev

### PR DESCRIPTION
**Pull request by DrewTCurrie**
# Created a new QR code and Badge generator program

## This will create QR codes that are transparent background and follow PTC's colors:
<details>
  <summary>New QR Code</summary>
  
</details>

## The badge templates are now setup to not have the logo cut off when printing on the PVC card printer
Additionally, the new badge generator calculates the width of the QR code and the template and automatically centers the QR code. This was also repeated with the text so that the text is always centered regardless of how long it is. This is actually pretty neat the way it works but does slow down the code a bit
### Employee Badges:
<details>
  <summary>Employee Front</summary>
  
</details>

<details>
  <summary>Employee Back</summary>
  
</details>

### Client Badges:
<details>
  <summary>New Client Front</summary>
  
</details>

## Updated app.py
The app.py was updated with the new badge generator however, I just imported it and called it the same name as the old one so we can revert if there is an issue on the Pi.

``` python
from APIFuncs import badgeGenerator_v2 as badgeGenerator
```

### Performance: 
This code is much slower, the time to create a badge now approaches 30 seconds. However, this is still well within the 5 minute time limit. This is because handling all the transparencies properly takes some compute time. This will need to be timed on the real system. There are likely spots that can be optimized but I am too tired to figure that out tonight. 

### Misc.
I found a few other small things that needed updating, ie gitignore, vite config, etc. These were also done in this although probably should have been committed directly to dev. 

### Remaining tasks:
The print button the Admin UX still needs to not open the print preview but instead download the images. That should be fairly easy to implement. I did not change the return of the badges to the Admin UX at all so the Admin UX does not notice a difference.

### CODE REVIEW

**Comment by DrewTCurrie** [comment]
Just realized it might be close on the big peach tree logo to the slot. If it is I'll have to change the picture location and shift it down. But that will require a test print most likely

**Comment by samlovering** [comment]
I have a couple things that I think should be changed.

The box size for the QR code should be reduced for 10. 15-30 seconds is about 15X slower than before, we should try to reduce this. Because the badge is small, the resolution shouldn't really matter.

The Employee front may need to be shifted downwards about 15% for a slot for the ID.
The Employee back logo in the corner should either be removed or centered above the QR code.

**Review by samlovering — CHANGES_REQUESTED** [review]
See comment, being picking on formatting + reducing QR box size

Additionally, I notice numpy is imported, but not used anywhere?

**Review by samlovering — APPROVED** [review]

**Comment by DrewTCurrie** [comment]
Updated badge generator to make faster badges, and updated templates so nothing gets cut off. 
 
<details>
  <summary>Time generate badges</summary>
  
</details>

<details>
  <summary>New Employee Badges</summary>
  
  
</details>

<details>
  <summary>New QR Codes With Gradient Image</summary>
  
</details>

**Pull request merged**
